#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -eou pipefail

function main {
  grep ".*\.\(cjs\|js\|ts\|tsx\)" ./checksums/sums.md5 \
    | md5sum --check --quiet &> /dev/null
}

main
